export const imageDescriptions: Record<string, string> = {
  "2 Dot Bottle and Carved Vase": "Amber bottle with two large circular dot stamps paired with cream carved vase",
  "2 Leaf, 1 Pepper": "Three white bowls with spiral centers photographed outdoors on brick pavers",
  "Amber Banded Bottle Narrow": "Tall bottle with horizontal amber and brown banded texture creating striped pattern",
  "Amber Berry Bowl Colander": "Berry bowl colander with drainage holes in amber glaze with dark brown exterior gradient",
  "Amber Bottle And Berry Bowl": "Amber bottle with single eye-like dot stamp paired with matching colander bowl",
  "Amber Bowl Carving Detail": "Close-up detail of red-brown bowl with carved leaf decorations",
  "Amber Bowl Glaze Macro": "Macro photograph showing amber glaze speckled texture and crystalline surface",
  "Amber Carved Bowl Angle": "Angled view of ribbed amber bowl with blue-speckled cream interior",
  "Amber Carved Bowl Top View": "Overhead view of amber bowl with carved ribbed texture and maker's stamp",
  "Amber Eye Bottle": "Tall amber speckled bottle with two large circular stamps resembling watching eyes",
  "Amber Gradient Bottle Tall": "Suspended tall bottle with smooth dark brown to amber gradient glaze",
  "Amber Honey Spiral Bowls": "Two amber bowls with spiral centers and blue gradient exterior on wooden surface",
  "Amber Ribbed Bowl Overhead": "Overhead interior view of berry bowl showing drainage holes and amber glaze pooling",
  "Amber Speckled Platter": "Wide shallow platter with cream glaze featuring '20' stamp in dark brown center",
  "Amber Speckled Vase": "Stacked amber lidded jar and vase with cream glaze and basketweave carved texture",
  "Amber Textured Bowl Side": "Close-up of cup with textured surface showing blue, brown, and cream glaze interaction",
  "Amber Yarn": "Two amber yarn bowls with yarn guide notches displayed with bamboo board showing function",
  "Anatomical Figure Mug Portrait": "Brown metallic glaze mug with white medallion featuring anatomical figure transfer",
  "Angular Pottery Arrangement": "Collection of faceted geometric pottery in pink, amber, and cream arranged on bamboo mat",
  "Angular Pottery Final Image": "Three angular faceted bottles in earth tones grouped together",
  "Array of Colorful Mugs": "Nine ribbed mugs in purple, amber, teal, and brown glazes displayed together",
  "Berry Bowl": "Cream and amber striped berry bowl with central drainage holes for rinsing fruit",
  "Berry Bowl and Two Ashtrays": "Amber berry bowl colander with two matching round ashtrays featuring spiral centers",
  "Berry Bowl With Drainer": "Functional amber yarn bowl with yarn guide slot on weathered brick surface",
  "Bird Lady Mug": "Hand holding amber mug with white medallion showing anatomical heart transfer",
  "Birdperson": "Cream speckled serving tray with red birdperson cartoon character transfer",
  "Birdperson 2": "Brown mug with pale blue medallion featuring anthropomorphic bird character in suit",
  "Blue Berry Bowl Angle": "Three small flasks with leaf, chicken, and mushroom transfers in speckled amber glaze",
  "Blue Berry Bowl Colander": "Blue and cream footed bowl with hand-carved checkerboard texture and dark interior",
  "Blue Bowl": "Blue footed bowl with cream interior creating two-tone split design with carved base",
  "Blue Brown Yarn Bowl Angled": "Yarn bowl photographed outdoors showing blue and brown glaze cascade",
  "Blue Brown Yarn Bowl Interior": "Overhead interior view of yarn bowl revealing brown glaze and yarn guide slot",
  "Blue Brown Yarn Bowl Outdoor View": "Blue yarn bowl photographed on brick pavers in natural outdoor setting",
  "Blue Brown Yarn Bowl Overhead": "Yarn bowl photographed from above on brick showing brown interior and form",
  "Blue Crackle Mug Detail": "Amber mug with circular black logo stamp showing deliberate crackle glaze effect",
  "Blue Oil Bottle": "Green glossy oil bottle with metal pourer spout and yellow rubber gasket",
  "Botanical Collection Group": "Collection including monstera mugs, leaf flasks, and drip glaze vessels arranged together",
  "Bottle n Vase": "Amber bottle with two dot stamps next to cream vase with carved geometric pattern",
  "Bottle with Gold Transfer": "Purple gradient bottle with gold lustre botanical transfer, front view",
  "Bottle with Gold Transfer 2": "Purple gradient bottle with gold lustre botanical transfer, overhead angle",
  "Bowl with Three Dots": "Two cream bowls with amber interiors each featuring three circular dot stamps",
  "Brown Blue Bowl Detail": "Two small planters with ferns, one amber with heart transfer, one pink with moon",
  "Brown Blue Bowl Interior": "Two amber planters with anatomical heart transfers shown with potted ferns",
  "Brown Bowl Interior Glaze": "Pink planter with koi fish transfer shown from side angle with fern",
  "Brown Bowl Interior Pattern": "Macro detail showing microcrystalline brown glaze pattern inside bowl",
  "Brown Bowl Pattern Macro": "Extreme close-up of microcrystalline glaze showing textured brown surface crystals",
  "Brown Carved Feather Bowl": "Wide brown bowl with carved feather or leaf band pattern and dark interior",
  "Brutalist Jar": "Amber lidded jar and cream vase stacked vertically showing bold geometric forms",
  "Burnt Plate": "White plate photographed outdoors with heavy brown iron spotting from wood or soda firing",
  "Butterfly Mug Angle View": "Two pink and cream ribbed mugs with butterfly, snail, and shell transfers",
  "Butterfly Mug Dark Blue": "Three pink ribbed mugs featuring various anatomical and natural history transfers",
  "Carved Foliage Vase Back": "Back view of tall vase with deeply carved foliage on cream upper half and black lower half",
  "Carved Foliage Vase Front with Logo": "Front of carved foliage vase showing penguin logo visible through carved window opening",
  "Carved Honey Amber Bowl": "Wide amber bowl with carved exterior texture and brown interior from front angle",
  "Carved Texture Bowl Brown Interior": "Amber bowl showing carved exterior texture and rich brown interior glaze",
  "Carved Wing Mug": "Red earthenware cup with white porcelain slip featuring carved wing or feather designs",
  "Celadon Bowls": "Pair of celadon carved bowls, one with glossy black interior, one with brown spiral center",
  "Celadon Bowls 2": "Two jade-green celadon bowls with carved dot patterns and varying interior glazes",
  "Celadon Carved Texture Cup": "Celadon cup with carved triangle stamps and geometric decorations on exterior",
  "Celadon Triangle Cup": "Celadon cup photographed from above showing triangle decorations and cream interior",
  "Charcuterie Board and Eye Mug": "Cream speckled tray with cow butcher diagram paired with amber mug featuring eye stamp",
  "Charcuterie Tray": "Cream speckled serving board with red cow butcher's chart transfer decoration",
  "Chattered Pearly Bowl": "Two amber bowls with pearlescent cream interiors and carved geometric texture on bases",
  "Chicken Mug Collection": "Stack of seven brown mugs with red rooster transfers in white oval medallions",
  "Chicken Mugs": "Three brown ribbed mugs with red chicken silhouette transfers photographed laying flat",
  "Chopstick Bowls": "Two amber bowls with built-in chopstick rests on rims and oval slot details",
  "Close Up Dots": "Macro detail photograph showing pink circular dot stamps on cream pottery surface",
  "Close Up Glaze Texture": "Extreme macro of amber glaze showing orange iron oxide spot detail",
  "Collection Display": "Mushroom flask, cityscape mug, dotted bowl, and plate arranged with bamboo mat",
  "Cream Bowl with Shapes": "Two cream nesting bowls with rectangle stamp decorations and amber interiors",
  "Cream Nesting Bowls Pair": "Pair of cream nesting bowls with amber interiors showing dot stamps inside one bowl",
  "Dark Metallic Glaze Mug": "Dark gunmetal metallic mug with iridescent surface showing wheel throwing lines",
  "Dark Ocean Blue Pour Cup": "Deep blue textured pour cup with cream rim and organic pouring spout",
  "Daylily Vase Garden Close Up": "Small vase in grass holding orange daylily bloom with blue base and cream neck",
  "DISH": "Black mug with white circular medallion featuring weathervane or radio tower transfer",
  "Dots n Transfers": "Three mugs showing front transfers including reel-to-reel tape, bicycle, and alligator with dots",
  "Dots n Transfers From the Back": "Back view of three mugs with various transfers and pink dot stamp patterns",
  "Dots Set": "Bowl, cup, and mug set in cream glaze with pink circular dot stamp decorations",
  "Earth Berry Bowl Interior": "Interior view of earth-toned berry bowl showing drainage hole pattern and amber glaze",
  "Earth Colander": "Complete earth-toned berry bowl colander showing full form with amber exterior glaze",
  "Earthy Carved Mugs": "Three earth-toned mugs with deeply carved geometric patterns in brown and amber",
  "Earthy Teapot": "Round teapot with carved texture in earth tones featuring green and amber glazes",
  "Faceted Bottle Forms": "Three faceted geometric bottles in pink, amber, and cream tones showing angular planes",
  "Faceted Collection Complete": "Complete collection of angular faceted pottery vessels arranged together",
  "Faceted Form Macro Detail": "Macro detail photograph of faceted pottery edge showing crisp angular geometry",
  "Faceted Teapot Outdoor Light": "Faceted geometric teapot in amber photographed outdoors in natural sunlight",
  "Faceted Teapot Warm Amber": "Amber faceted teapot with geometric planes photographed in warm studio lighting",
  "Feather Bowl Edge Macro": "Extreme close-up of carved feather pattern detail on pottery bowl rim edge",
  "Flask n Juicer": "Amber citrus juicer paired with green drip glaze flask photographed outdoors",
  "Fractured Red Mug": "Black mug with fractured red glaze pattern creating organic crackled texture",
  "Frosty Glaze Crystals": "Macro detail of frosty microcrystalline glaze showing ice-like crystal formation",
  "Frosty Glaze Crystals 2": "Another view of frosty crystalline glaze texture on pottery surface showing crystals",
  "Gaiwan and 2 Bowls in the Wild": "Traditional Chinese tea set including gaiwan and bowls in outdoor natural setting",
  "Gear - Whale - Eye Mugs": "Three small flasks with mechanical gear, whale, and eye transfers in varied glazes",
  "Geometric Bottle Collection": "Collection of faceted geometric bottles in various earth tone glazes",
  "Geometric Collection Wide": "Wide panoramic view of complete angular pottery collection arranged together",
  "Geometric Teapot": "Faceted geometric teapot with angular planes and warm amber glaze finish",
  "Gold Butterfly Bottle": "Purple gradient bottle with gold lustre butterfly transfer decoration",
  "Gold Leaf Sipper": "Sipper cup with gold lustre leaf transfer on purple gradient glaze background",
  "Gold Lustre Set": "Collection of pottery pieces featuring gold lustre transfers on various colored backgrounds",
  "Gold Mayan Mug Set": "Set of six brown cylindrical cups with gold Mayan glyph transfer decorations on bamboo tray",
  "Gold Mayan Mug Set 2": "Three brown cylindrical mugs with gold Mayan glyph transfers photographed on bases",
  "Gold Mayan Sipper": "Brown sipper cup featuring gold Mayan glyph transfer decoration on side",
  "Gold Moon Vase": "Cream vase with gold lustre crescent moon transfer decoration",
  "Gold Turing Pattern Sippers": "Collection of sipper cups featuring gold Turing reaction-diffusion pattern transfers",
  "Gold Turing Pattern Sippers 2": "Sippers with gold pattern transfers on gradient glazes, alternative angle view",
  "Gold Turing Pattern Sippers 3": "Third angle showing sippers with gold Turing pattern decoration details",
  "Green Berry Bowl Colander": "Green gradient berry bowl with drainage holes and cream interior for fruit washing",
  "Green Berry Bowl Interior": "Interior view of green gradient berry bowl showing drainage hole pattern",
  "Green Brown Bowl Interior": "Bowl interior showing blended green and brown glaze interaction and pooling",
  "Green Gradient Berry Bowl": "Green gradient berry bowl exterior view showing smooth color transition down sides",
  "Green Gradient Yarn Bowl": "Yarn bowl in green gradient glaze with built-in yarn guide slot for knitting",
  "Green Lamp": "Green glazed ceramic lamp base with textured surface and electrical hardware",
  "Green Leaf Flask": "Green flask with carved or stamped leaf decoration on flattened surface",
  "Green River Plate": "Plate with flowing green glaze creating river-like pattern across surface",
  "Green Tea Bowls Stacked": "Stack of three jade-green celadon tea bowls showing varied glaze color effects",
  "Green Yarn Bowl Interior": "Interior view of green gradient yarn bowl showing yarn guide slot and throwing rings",
  "Hey": "Experimental pottery piece with unique multi-colored glaze combination and organic form",
  "Honey Banded Lidded Jar": "Lidded storage jar with honey amber horizontal bands and cream base",
  "Honey Jar Overhead View": "Overhead view of lidded honey jar showing amber glaze pooling on lid top",
  "Horizon Plates": "Three plates with dramatic horizon line glaze patterns in amber and brown earth tones",
  "In the Studio": "Behind-the-scenes photograph of pottery pieces arranged in ceramic studio workspace",
  "Iron Cup": "Cup with heavy iron oxide spotting creating dramatic dark speckled surface pattern",
  "Koi And Monstera Flasks": "Two flasks side by side, one with koi fish transfer, one with monstera leaf",
  "Lamp - Planter - Mug": "Three functional ceramic pieces including lamp base, planter, and decorative mug",
  "Lamp - Vase - Ashtray": "Functional pottery set including lamp base, vase, and ashtray with varied glazes",
  "Landscape Mugs": "Five mugs with carved landscape silhouettes and amber drip glazes in earth tones",
  "Large Bowl with Dots": "Large cream serving bowl with circular pink dot stamp decorations scattered on surface",
  "Layered Glaze Bottle": "Bottle with multiple layered glazes creating depth and color variation effects",
  "Leaf Flask - Reed Vase - Monstera Mug": "Three botanical pieces with leaf, reed, and monstera transfer decorations",
  "Leaf Teapot": "Round teapot with leaf-themed decoration in green gradient glaze finish",
  "Leaf Trio": "Three pottery pieces featuring leaf motifs stamps or carved decorations",
  "Lil Fellas Paperweight": "Small decorative paperweight with figured or character design element",
  "Lil People Planter": "Small planter featuring miniature figure or character decoration detail",
  "Lil People Planter 2": "Alternative view of small planter with figural decorative element",
  "Logo Foot": "Close-up photograph of pottery base showing impressed maker's logo stamp on foot ring",
  "Logo on Clay": "Detail shot of penguin logo stamp impressed into raw clay surface before firing",
  "Logo Vase": "Tall vase with deeply carved penguin logo creating dramatic black and cream contrast",
  "Luciann Theater Tray": "Decorative serving tray with theater-themed imagery or text decoration",
  "Mayan Glyph Bottle": "Bottle featuring Mayan glyph transfer decoration in contrasting glaze colors",
  "Mayan Gold Glyph Tumblers": "Set of tumblers with gold lustre Mayan glyph transfer decorations",
  "Metallic Glaze Cup Trio": "Three cups with metallic or iridescent glaze effects in varied colors",
  "Microcrystaline Delight": "Close-up of microcrystalline glaze with dramatic golden yellow crystal pattern formation",
  "Microcrystaline Delight 2": "Second view of microcrystalline glaze showing detailed crystal formation and texture",
  "Microcrystaline Funk": "Experimental microcrystalline glaze showing unique crystal effects and unusual coloration",
  "Microcrystaline Funk 2": "Alternative angle of microcrystalline glaze with unique color and pattern development",
  "Microcrystaline Glaze Dots": "Pottery combining microcrystalline glaze effects with circular dot stamp decoration",
  "Midnight Blue Pour Cup": "Deep midnight blue pour cup with smooth glossy finish and organic form",
  "Moon Jug": "Rounded jug with crescent moon transfer decoration in gold or dark glaze",
  "Moon Jug Outdoors": "Moon-decorated jug photographed in outdoor natural setting with foliage",
  "Moon Mug": "Green mug with large cream circular moon medallion featuring iron oxide spotting",
  "Moon Mug Collection": "Collection of mugs featuring crescent moon phase transfer decorations in varied glazes",
  "Moon Mug Pink Flash": "Moon mug with pink flash glaze creating subtle iridescent color shifting effect",
  "Moon Mugs Outdoors": "Multiple moon-decorated mugs arranged outdoors for natural light photography",
  "Moss Green Narrow Neck Vase": "Slender vase with narrow neck opening in matte moss green glaze finish",
  "Mr.Sausage Tray": "Serving tray featuring dachshund or sausage dog butcher chart transfer decoration",
  "Mr.Sausage Tray 2": "Alternative angle of serving tray with sausage dog butcher diagram imagery",
  "Mr.Sausage Tray 3": "Third view of decorative tray featuring dachshund butcher chart design",
  "Mr.Skeltal Mug": "Mug with skeleton or anatomical skeleton transfer decoration on dark background",
  "Mugs in the Kilnyard": "Collection of finished mugs photographed in outdoor kilnyard area workspace",
  "Mushroom And Koi Flask Collection": "Flasks featuring mushroom and koi fish transfer decorations grouped together",
  "Mushroom Flasks Paired": "Two flasks with detailed mushroom transfer decorations displayed side by side",
  "Nesting Bowls": "Set of three nesting bowls in graduated sizes with amber interiors and cream exteriors",
  "Off the Beaten Path Gallery Show at Northwestern University": "Display photograph from pottery exhibition at Northwestern University gallery",
  "Oil Bottle": "Bottle designed for oil storage with integrated pourer spout for controlled dispensing",
  "Orange 3 Dots Paperweight": "Orange paperweight featuring three circular dot stamp decorations on surface",
  "Orange Bottle with Gold Flowers": "Orange gradient bottle featuring gold lustre floral transfer decoration",
  "Orange Bowl and Mushroom Flask at the Studio": "Orange bowl paired with mushroom transfer flask in ceramic studio setting",
  "Orange Paperweight": "Solid orange spherical or rounded paperweight form in bright glaze",
  "Orange Sipper Collab (Raquel Hung)": "Orange sipper cup, collaborative pottery work with artist Raquel Hung",
  "Orange to Black Vase": "Vase with dramatic gradient transitioning from orange top to black base",
  "Organic Fused Vases": "Sculptural vases with organic fused or melted appearance and flowing forms",
  "Organic Fused Vases 2": "Second view of organic sculptural vases with fused melted texture effects",
  "Organic Fused Vases 3": "Third angle of organic vases with dramatic flowing fused form design",
  "Oribe Vase": "Vase with traditional Japanese oribe green copper glaze finish technique",
  "Painted Honey Bowl Interior View": "Interior view of honey amber bowl showing painted or carved interior decoration",
  "Pepper Bowls": "Bowls featuring pepper shape stamp or transfer decorations on surfaces",
  "Pink Berry Bowl And Plate": "Pink berry bowl with drainage holes paired with matching drip collection plate",
  "Pink Berry Bowl Detail": "Detail view of pink berry bowl showing drainage hole pattern and texture",
  "Pink Berry Bowl With Plate": "Pink functional berry bowl arranged on coordinating collection plate",
  "Pink Bowl Interior Glaze": "Interior view showing pink glaze pooling and color variation inside serving bowl",
  "Pink Glaze on Black BMIX Mug": "Black BMIX clay mug with contrasting pink glaze creating dramatic color effect",
  "Pink Glaze on Black BMIX Mug 2": "Second example of black BMIX clay mug with pink glaze decoration",
  "Pink Mug Interior Detail": "Close-up of pink-glazed mug interior showing glaze pooling and color variation",
  "Portafilter Mug": "Mug designed with espresso portafilter machine aesthetic and spout form",
  "Portafilter Mugs": "Pair of cream mugs with blue dipped bases featuring portafilter and moka pot transfers",
  "Portafilter Pair": "Two espresso portafilter-inspired mugs paired together showing complementary designs",
  "Pottery Collection Rooftop Wide": "Wide panoramic view of pottery collection displayed on urban rooftop setting",
  "Pottery in the Kilnyard": "Various pottery pieces arranged outdoors in kilnyard workspace area",
  "Purple Black Gradient Mug": "Mug with dramatic purple fading to black gradient glaze creating color shift",
  "Purple Blue Gradient Bowl One": "Bowl with purple to blue gradient glaze, first of documentation series",
  "Purple Blue Gradient Bowl Three": "Third view of purple to blue gradient bowl showing interior color blend",
  "Purple Blue Gradient Bowl Two": "Second angle of purple to blue gradient bowl showing form and glaze",
  "Purple Gradient Mug": "Mug with soft purple gradient glaze flowing down sides like twilight colors",
  "Purple Gradient Mug Detail": "Detail photograph of purple gradient mug showing smooth color transition zones",
  "Purple Green Anatomical Mug": "Mug with purple and green glazes featuring anatomical heart transfer decoration",
  "Purple Green Bowl Edge Detail": "Macro detail of bowl edge showing purple and green glazes meeting organically",
  "Purple Green Bowl Interior": "Interior view of bowl showing purple and green glaze blend and interaction",
  "Radio Freak Bowls": "Collection of bowls featuring radio frequency or electronics-themed transfer decorations",
  "Radio Freak Bowls 2": "Second view of bowls with radio or electronic equipment transfer imagery",
  "Radio Freak Mug - Zoomed": "Close-up zoom photograph of mug with radio frequency or electronics transfer",
  "Radio Head Mug": "Mug with radio or head-themed transfer decoration on dark background",
  "Rainy Jar": "Rounded jar with rain-like drip glaze pattern texture in blue-green tones",
  "Rainy Jar Outdoors": "Rain pattern jar photographed in outdoor garden setting with natural light",
  "Randy's Red on Black BMIX": "Red glaze on black BMIX clay body showing dramatic high-contrast color effect",
  "Randy's Red on Black BMIX Mug Bottom": "Bottom view of black BMIX clay mug showing red glaze and base",
  "Raw Clay Vase": "Vase in raw unglazed state showing natural clay body color and texture",
  "Red Stripe Bowl": "Bowl with red horizontal stripe or band decoration across midsection",
  "Ribbed Cups": "Pair of cream cups with horizontal ribbed carved texture and brown inlaid clay panels",
  "Rusty Water Flask": "Flask with rusty red and black water-like glaze effect creating organic pattern",
  "Sake Set": "Traditional sake serving set with bottle and five small cups on bamboo tray",
  "Scenery Planter": "Planter with landscape or scenery transfer decoration showing outdoor imagery",
  "Self Portrait Vase": "Vase featuring artist's self-portrait transfer or imagery decoration",
  "Self Portrait Vase 2": "Alternative angle of vase with artist's self-portrait decoration visible",
  "Self Portrait Vase in Greenery": "Self-portrait decorated vase photographed among plants and garden greenery",
  "Shell - Gear - Nude Mug": "Mug with shell, mechanical gear, and figure transfer decorations combined",
  "Small Green Daylily Vase": "Small green vase designed for single flower stem display in garden",
  "Snail Mug Collab (Raquel Hung)": "Mug with detailed snail transfer, collaborative work with artist Raquel Hung",
  "Snail Mugs Collab (Raquel Hung)": "Pair of cups with detailed snail transfers, collaboration with Raquel Hung",
  "Soft Cream Nesting Bowls": "Set of nesting bowls in soft cream glaze with gentle forms for everyday use",
  "Spiral Bowls": "Two bowls with deeply carved spiral centers, one with black interior, one with amber",
  "Stacked Bowls": "Multiple bowls stacked vertically for display showing varied glaze effects",
  "Stacked Colorful Mugs": "Vertical stack of colorful glazed mugs showing variety of finishes and colors",
  "Sunrise Mugs": "Pair of dark blue-black mugs with carved sunrise or sunburst cream medallions",
  "Sunrise Pair": "Two mugs with sunrise-themed carved decoration in dramatic dark and light contrast",
  "Suspended Plates": "Plates suspended or hung vertically for dramatic shadow and form display",
  "Symbol Mugs": "Six mugs in amber and black with carved geometric symbol decorations including circles and shapes",
  "Textured Chunky Glazed Bowl": "Bowl with heavy thick chunky glaze application creating dramatic textured surface",
  "Textured Cup": "Cup with applied textured surface decoration showing blue, brown, and cream glaze blend",
  "Textured Earth Mug Carved": "Earth-toned mug with deliberately carved surface texture catching light dramatically",
  "Textured Orange And Black Bowl": "Bowl with heavily textured rough exterior in orange and black volcanic-like glaze",
  "Textured Orange Mugs": "Set of orange mugs with hand-carved textured surfaces in warm earth tones",
  "Three Bowls on the Wall": "Three bowls mounted or displayed on wall showing forms and glazes",
  "Three Carved Mugs": "Set of three mugs with deeply carved texture decoration on surfaces",
  "Three Flasks": "Trio of small flasks in varying glazes arranged together showing size and form",
  "Tiki Cocktail Bowl": "Bowl designed for tiki cocktail serving with tropical aesthetic and form",
  "Tiki Cocktail Vessel": "Blue sculptural tiki-style cocktail vessel with organic rounded form",
  "Triple Layer Gradient Mug": "Mug featuring three distinct glaze gradient layers from blue to brown to black",
  "Vaporwave Jar": "Lidded jar with vaporwave aesthetic featuring pink, cream, and green gradient colors",
  "Weathervane Sipper": "Sipper cup with weathervane or directional arrow transfer decoration",
  "Weathervane Sipper 2": "Second view of sipper with weathervane transfer showing different angle",
  "Weathervane Sipper 3": "Third angle of weathervane sipper cup showing transfer decoration detail",
  "Whale Oil Bottle": "Oil bottle with whale transfer decoration on green glazed surface",
  "White Lidded Jar Cork Top": "White glazed lidded jar topped with natural cork stopper for storage",
  "Wrinkly Soda Fired Green Glaze": "Green soda-fired glaze with dramatic wrinkled texture from firing process",
  "Yarn Bowl And Garlic Keeper": "Functional set including yarn bowl with slot and garlic storage keeper with holes",
  "Zoomed Glaze": "Extreme macro zoom photograph of glaze surface showing texture and color detail",
};
