const imageDescriptions: Record<string, string> = {
  "Adult Memes Mug Base View": "Base and interior of adult-themed transfer mug",
  "Adult Memes Mug Collection": "Collection of mugs featuring playful adult-themed transfers",
  "Adult Memes Mug Handle Side": "Handle-side view of playful adult transfer mug",
  "Adult Memes Mug Side Angle": "Angled view showing transfer text on mug surface",
  "Adult Memes Mug Side Detail": "Side detail of mug with adult meme text transfers",
  "Amber Banded Bottle Narrow": "Narrow bottle with amber glaze bands, horizontal stripes like desert sandstone layers",
  "Amber Berry Bowl Colander": "Berry bowl colander in amber glaze, functional form meeting beautiful surface",
  "Amber Bottle And Berry Bowl": "Amber bottle paired with functional berry bowl, complementary forms",
  "Amber Bowl Carving Detail": "Detail of carving on amber bowl",
  "Amber Bowl Glaze Macro": "Macro detail of amber glaze surface showing crystals",
  "Amber Bowl Interior Carving": "Interior view showing carved pattern",
  "Amber Bowl Portrait Detail": "Portrait detail of amber bowl carving",
  "Amber Bowl Portrait View": "Portrait-oriented view of amber bowl",
  "Amber Bowl Speckling Detail": "Close detail of amber bowl with iron speckling",
  "Amber Bowl Texture Close": "Close texture detail of amber bowl",
  "Amber Bowls Geometric Pattern": "Amber bowls featuring carved geometric patterns, angular designs meeting organic form",
  "Amber Carved Bowl Angle": "Angled view of carved amber bowl",
  "Amber Carved Bowl Set": "Set of amber carved bowls displayed",
  "Amber Carved Bowl Top View": "Top view of amber bowl with carved details",
  "Amber Eye Bottle": "Bottle in amber glaze with carved eye motif, watchful gaze fixed in clay",
  "Amber Eye Bottle And Cream Vase": "Amber eye bottle paired with cream vase, contrasting forms in dialogue",
  "Amber Flask And Bowl Set": "Amber flask and bowl in complementary tones",
  "Amber Flask Botanical Transfer": "Amber flask with botanical transfer imagery",
  "Amber Flask Evening Light": "Amber flask photographed in evening light, warm tones emphasized",
  "Amber Geometric Bowls Paired": "Paired amber bowls with complementary geometric surface treatments",
  "Amber Gradient Bottle Tall": "Tall bottle transitioning from dark amber base to honey-lit rim, gradient smooth as sunset",
  "Amber Gradient Bowl Side": "Bowl showing amber glaze gradient, color transitioning smoothly",
  "Amber Honey Bowls Set One": "Set of bowls in honey-amber tones",
  "Amber Honey Bowls Set Three": "Third view of honey-amber bowl collection",
  "Amber Honey Bowls Set Two": "Additional view of amber honey bowl set",
  "Amber Honey Jar Close": "Close view of amber honey-toned jar",
  "Amber Honey Spiral Bowls": "Bowls in honey-amber tones with spiral carved details, warm as stored sunlight",
  "Amber Jar Close Detail": "Close detail of amber jar surface and glaze",
  "Amber Jars Lidded Pair One": "Pair of lidded jars in amber glaze",
  "Amber Jars Lidded Pair Two": "Alternative view of amber lidded jar pair",
  "Amber Lidded Jars Group": "Group of amber lidded storage jars",
  "Amber Ribbed Bowl Overhead": "Overhead view of amber ribbed bowl showing form",
  "Amber Ribbed Vase": "Vase with pronounced ribbed texture in amber tones",
  "Amber Speckled Bowl Interior": "Interior of amber bowl with metallic speckling",
  "Amber Speckled Bowl Side": "Side view of amber speckled serving bowl",
  "Amber Speckled Jar Lid One": "Amber speckled jar with fitted lid",
  "Amber Speckled Jar Lid Two": "Another perspective on amber speckled lidded jar",
  "Amber Speckled Mugs Matching Pair": "Matching pair of amber-speckled mugs, surfaces dotted like bird eggs",
  "Amber Speckled Vase": "Vase in amber with dark speckles scattered across surface like seeds",
  "Amber Textured Bowl Side": "Side view of textured amber bowl",
  "Amber Yarn Bowl Close View": "Close perspective on amber yarn bowl, glaze details and texture intimately revealed",
  "Amber Yarn Bowl Solo": "Single amber yarn bowl, warm tones glowing against dark background",
  "Amber Yarn Bowls Pair": "Pair of yarn bowls in warm amber tones, honey-colored glaze pooling like afternoon sunlight",
  "Anatomical Figure Mug Portrait": "Portrait-oriented mug with anatomical figure transfer",
  "Anatomical Heart Mug Side": "Side view of mug featuring anatomical heart transfer",
  "Angular Forms Composition": "Compositional arrangement of angular forms",
  "Angular Pottery Arrangement": "Arrangement highlighting angular pottery forms",
  "Angular Pottery Final Image": "Final image of angular pottery collection",
  "Angular Vase Close Study": "Close study of angular vase form",
  "Angular Vessels Group": "Group of angular geometric vessels",
  "Basketweave Texture Lidded Jar": "Lidded jar textured with basketweave pattern, woven clay meeting amber glaze",
  "Berry Bowl With Drainer": "Functional berry bowl with integrated drainer, holes forming constellation patterns",
  "Black Anatomical Mugs Set": "Set of black mugs with anatomical transfers",
  "Black Green Swirl Plate": "Plate with dramatic black and green swirling glaze",
  "Blue And Pink Gradient Mugs": "Mugs featuring blue and pink gradient glazes",
  "Blue And White Mugs Group": "Group of mugs in blue and white color scheme",
  "Blue Berry Bowl Angle": "Angled view of blue berry bowl showing form and function",
  "Blue Berry Bowl Colander": "Functional berry bowl in blue glaze with drainage perforations",
  "Blue Brown Yarn Bowl Angled": "Angled perspective of yarn bowl revealing interplay of cobalt blue and sienna brown glazes",
  "Blue Brown Yarn Bowl Interior": "Interior view of yarn bowl revealing concentric throwing rings, glazed in deep ocean blues meeting warm brown earth",
  "Blue Brown Yarn Bowl Outdoor View": "Yarn bowl photographed in natural light, blue mountain glazes cascading into brown valley depths",
  "Blue Brown Yarn Bowl Overhead": "Overhead view into yarn bowl's spiral interior, glazes swirling like potter's wheel memory",
  "Blue Brown Yarn Bowl Side View": "Wheel-thrown yarn bowl with cascading blue and earthy brown glazes, white drips frozen mid-flow down textured sides",
  "Blue Crackle Bowls": "Bowls featuring blue crackle glaze, deliberate crazing adding texture",
  "Blue Crackle Bowls Pair One": "Pair of blue crackle glaze bowls",
  "Blue Crackle Bowls Pair Two": "Additional view of blue crackle bowl pair",
  "Blue Crackle Mug Detail": "Detail view of blue crackle glaze, crazing pattern visible",
  "Blue Dipped Footed Bowl Pedestal": "Footed bowl dipped in blue glaze, elevated form like offering vessel",
  "Blue Green Mugs Set Five": "Final view completing blue-green mug documentation",
  "Blue Green Mugs Set Four": "Fourth perspective on blue-green mug series",
  "Blue Green Mugs Set One": "Set of mugs in blue-green tones, cool color palette",
  "Blue Green Mugs Set Three": "Third view of blue-green mug collection",
  "Blue Green Mugs Set Two": "Additional blue-green mugs, complementary forms",
  "Blue Pedestal Yarn Bowl Elevated": "Yarn bowl elevated on pedestal foot, cobalt blue glaze pooling dramatically",
  "Blue Textured Yarn Bowl Close": "Close view of textured yarn bowl, cobalt blue glaze settling into every carved groove",
  "Botanical Collection Group": "Group arrangement of botanical-themed pottery, nature celebrated in clay",
  "Botanical Transfer Mugs Set": "Set of mugs with various botanical transfer designs",
  "Brown Blue Bowl Detail": "Close detail of brown and blue glaze meeting",
  "Brown Blue Bowl Interior": "Interior view of brown and blue glazed bowl",
  "Brown Blue Bowls Nested": "Nested bowls in brown and blue glazes, earthy meets aquatic",
  "Brown Blue Bowls Stacked": "Stack of brown and blue bowls showing glaze variations",
  "Brown Bowl Close Texture": "Close view of brown bowl showing surface texture",
  "Brown Bowl Interior Glaze": "Interior glaze of brown bowl, pooling and flow visible",
  "Brown Bowl Interior Pattern": "Interior of brown bowl showing stamped pattern detail",
  "Brown Bowl Pattern Macro": "Macro view of stamped pattern in brown bowl interior",
  "Brown Bowls Full Set": "Complete set of brown nesting bowls displayed",
  "Brown Bowls Graduated Sizes": "Graduated sizes of brown bowls, nesting set complete",
  "Brown Carved Feather Bowl": "Bowl in brown with carved feather pattern around rim",
  "Brutalist Jar": "Bold sculptural jar encrusted with organic textures, glazes bleeding across brutalist forms in amber and black",
  "Butcher Chart Serving Dish": "Playful serving dish emblazoned with butcher's chart, celebrating farm animals in ceramic form",
  "Butterfly Monstera Mug Pair": "Pair featuring butterfly and monstera transfers, nature united",
  "Butterfly Mug Angle View": "Angled view of butterfly transfer mug showing detail",
  "Butterfly Mug Dark Blue": "Dark blue mug featuring butterfly transfer, winged beauty preserved",
  "Carved Foliage Vase Back": "Reverse view of carved foliage vase revealing continued botanical narrative",
  "Carved Foliage Vase Front": "Vase with deeply carved foliage details, botanical forms emerging from clay",
  "Carved Honey Amber Bowl": "Bowl with carved exterior in honey amber glaze, light catching every groove",
  "Carved Texture Bowl Brown Interior": "Bowl with textured sand-colored exterior revealing rich brown interior landscape",
  "Carved Texture Bowls Set": "Set of bowls with varied carved textures, tactile surfaces inviting touch",
  "Carved Wing Mug": "Mug carved with wing motif, feathered forms ready for flight",
  "Celadon Carved Texture Cup": "Cup in pale celadon with carved surface texture, jade glaze settling into impressions",
  "Celadon Face Impression Cup": "Small celadon cup bearing soft face impression, pale green glaze pooling in gentle indentations",
  "Celadon Lidded Jar And Bowls": "Celadon lidded jar flanked by matching bowls, pale jade glaze unifying the collection",
  "City Life Transfer Bowl": "Bowl adorned with city dwellers in daily life, transfers capturing movement",
  "Crackle Glaze Mugs Display": "Display of mugs featuring crackle glaze finishes",
  "Cream Bowl Interior Spirals": "Interior view of cream bowl revealing spiral throwing marks, potter's touch visible",
  "Cream Nesting Bowls Pair": "Pair of cream nesting bowls, simple forms inviting everyday use",
  "Cream Square Bowls Nesting": "Nesting set of square-rimmed bowls in soft cream, geometric forms stacking precisely",
  "Dalmatian Speckled Jar": "Jar scattered with dark speckles against cream background, pattern random as dalmatian spots",
  "Dark Metallic Glaze Mug": "Mug cloaked in dark metallic glaze, surface shimmering with oil-slick iridescence",
  "Dark Ocean Blue Pour Cup": "Cup in deep ocean blue, glaze running like waves frozen mid-crash",
  "Daylily Vase Garden Close Up": "Vase photographed intimately among daylily blooms, ceramic and flora in conversation",
  "Death Star Transfer Mug": "Mug featuring Death Star transfer on black glaze",
  "Deep Blue Sun Flask": "Flask glazed in deep midnight blue, carved sun motif rising like dawn breaking",
  "Earth Berry Bowl Interior": "Interior view of earth-toned berry bowl, drainage holes visible from within",
  "Earth Tone Bottle Pourers Trio": "Three small bottle-form pourers in varied earth tones, functional sculpture",
  "Earth Tone Mugs Paired": "Pair of mugs in complementary earth tones, natural palette",
  "Faceted Bottle Forms": "Bottle forms with faceted geometric surfaces",
  "Faceted Collection Complete": "Complete faceted collection documentation",
  "Faceted Form Macro Detail": "Macro detail of faceted form surface",
  "Faceted Forms Final View": "Final view of faceted geometric forms",
  "Faceted Forms Tight Crop": "Tight crop on faceted geometric forms",
  "Faceted Forms Varied Sizes": "Faceted forms in varied sizes displayed",
  "Faceted Geometric Vessels Start": "Beginning of faceted geometric vessel series",
  "Faceted Teapot Outdoor Light": "Faceted teapot in natural outdoor light, geometric form creating shadow play",
  "Faceted Teapot Warm Amber": "Faceted teapot in warm amber tones, geometric planes catching and reflecting light",
  "Faceted Vases Angles Study": "Study of angles in faceted vase forms",
  "Faceted Vases Paired": "Paired faceted vases in complementary sizes",
  "Faceted Vessels Angles": "Faceted vessels showing angular geometric planes",
  "Faceted Vessels Light Study": "Light study on faceted vessel surfaces",
  "Faceted Vessels Lineup": "Lineup of faceted vessels showing form variety",
  "Faceted Vessels Series End": "End of faceted vessels documentation series",
  "Faceted Vessels Set Four": "Final perspective on faceted geometric pieces",
  "Faceted Vessels Set One": "Set of faceted geometric vessels",
  "Faceted Vessels Set Three": "Third view of faceted vessel collection",
  "Faceted Vessels Set Two": "Additional faceted vessels, geometric forms",
  "Feather Bowl Edge Macro": "Macro detail of carved feather pattern on bowl edge",
  "Forest Anatomical Mugs Pair": "Pair of forest-toned mugs with anatomical transfers",
  "Forest Green Moon Landscape Mug": "Mug adorned with misty forest landscape and crescent moon, evergreens emerging from deep green glaze like morning fog",
  "Forest Green Moon Mugs Pair": "Two mugs wrapped in forest green with crescent moon imagery, woodland magic captured",
  "Forest Mug Base Detail": "Base detail of forest green anatomical mug",
  "Forest Mugs On Wood Display": "Forest green mugs displayed on natural wood",
  "Geometric Bottle Collection": "Collection of geometric faceted bottles",
  "Geometric Collection Wide": "Wide view of geometric pottery collection",
  "Geometric Forms Collection": "Collection of geometric faceted pottery forms",
  "Geometric Forms Conclusion": "Conclusion of geometric forms photography",
  "Geometric Forms Display Board": "Geometric forms arranged on display board",
  "Geometric Forms End Shot": "Concluding shot of geometric forms series",
  "Geometric Forms Shadow Play": "Geometric forms creating interesting shadows",
  "Geometric Pottery Group Shot": "Group shot of geometric pottery collection",
  "Geometric Vase Details": "Detail view of geometric faceted vase",
  "Geometric Vessel Detail Close": "Close detail of single geometric vessel",
  "Geometric Vessels Close Group": "Close grouping of geometric vessels",
  "Geometric Vessels Last Angle": "Last angle on geometric vessel display",
  "Gradient Mug Texture Close": "Close texture detail of gradient glazed mug",
  "Gradient Mugs Color Study": "Study of gradient glaze effects across multiple mugs",
  "Green And Brown Bowl Close": "Close view of bowl with green and brown glazes meeting organically",
  "Green And Purple Bowls": "Bowls in complementary green and purple glazes",
  "Green Berry Bowl Colander": "Functional berry bowl colander in green glaze",
  "Green Berry Bowl Interior": "Interior of green gradient berry bowl with drainage",
  "Green Brown Bowl Interior": "Interior perspective revealing green and brown glaze interaction",
  "Green Gradient Berry Bowl": "Berry bowl with green gradient glaze, functional beauty",
  "Green Gradient Flask": "Flask showing green glaze gradient from dark to light",
  "Green Gradient Yarn Bowl": "Yarn bowl in green gradient, color flowing like forest canopy",
  "Green Monstera Bottle Set": "Set of green bottles with monstera leaf transfers",
  "Green Moss Bird Flask": "Flask in moss green with bird transfer imagery, avian forms in flight",
  "Green Moss Flask And Monstera Mug": "Moss green flask paired with monstera leaf transfer mug, botanical collection",
  "Green Tea Bowls Stacked": "Stack of green tea bowls, simple forms for mindful drinking",
  "Green Yarn Bowl Interior": "Interior of green gradient yarn bowl, throwing rings visible",
  "Green Yarn Bowl Side View": "Side perspective on green gradient yarn bowl",
  "Honey Banded Lidded Jar": "Lidded jar with honey-colored glaze bands",
  "Honey Jar Overhead View": "Overhead view of banded honey jar with lid",
  "Honey Striped Jar Top View": "Top view of honey jar showing concentric glaze bands",
  "Koi And Monstera Flasks": "Flasks decorated with koi fish and monstera leaf imagery, aquatic and botanical themes united",
  "Lets Sausage Bacon Dish Angle": "Angled view of playful butcher chart serving dish",
  "Logo Vase": "Tall cylindrical vase carved with bold penguin silhouette, black form emerging from cream background in graphic relief",
  "Luciano Party Ashtray": "Playful ashtray emblazoned with party text, whimsical functional form",
  "Midnight Blue Pour Cup": "Cup captured mid-glaze pour, deep midnight blues frozen in downward journey",
  "Monstera And Bird Mugs": "Mugs featuring monstera leaves and bird transfers",
  "Monstera Flask Botanical Detail": "Detail of monstera botanical transfer on flask",
  "Monstera Flask Detail": "Close detail of monstera leaf transfer on flask",
  "Monstera Leaf Mug Dark": "Dark mug adorned with monstera leaf transfer, tropical foliage captured",
  "Monstera Mug Collection": "Collection of monstera leaf transfer mugs, tropical theme",
  "Monstera Vessels Grouped": "Group of monstera-adorned vessels, botanical theme",
  "Moss Green Narrow Neck Vase": "Slender vase with narrow neck in moss green, elegant minimalist form",
  "Moss Leaf Teapot": "Teapot glazed in deep moss green, botanical essence captured in form",
  "Mugs In Wooden Crate Display": "Collection of mugs displayed in vintage wooden crate",
  "Mushroom And Koi Flask Collection": "Collection of flasks featuring mushroom and koi fish transfers, nature imagery in ceramic",
  "Mushroom Flasks Paired": "Pair of flasks adorned with mushroom transfers, fungi frozen in glaze",
  "Mushroom Transfer Flask Side": "Flask featuring mushroom transfer print, fungi in perfect detail",
  "Olive Green Stamped Plate": "Plate in olive green with stamped pattern details",
  "Olive Plate Detail Close": "Close detail of stamped olive green plate",
  "Painted Honey Bowl Interior View": "Interior of honey-toned bowl revealing painted details within",
  "Pink Berry Bowl And Plate": "Pink berry bowl paired with matching plate",
  "Pink Berry Bowl Detail": "Detail view of pink berry bowl drainage holes",
  "Pink Berry Bowl Functional Set": "Complete functional pink berry bowl with drainer",
  "Pink Berry Bowl Set Complete": "Complete pink berry bowl set with drainer and plate",
  "Pink Berry Bowl With Plate": "Pink berry bowl alongside matching drip plate",
  "Pink Bowl Interior Glaze": "Interior glaze detail of pink serving bowl",
  "Pink Flask And Mug Set": "Coordinated pink flask and mug with monstera leaves",
  "Pink Floral Transfer Mug": "Mug adorned with pink floral transfer imagery",
  "Pink Gradient Monstera Bottle": "Bottle with pink gradient and monstera transfers",
  "Pink Monstera Flask": "Flask in pink tones with monstera leaf transfer",
  "Pink Monstera Flask Close": "Close view of pink flask with botanical transfer",
  "Pink Monstera Mug Pair": "Pair of pink mugs featuring monstera leaf imagery",
  "Pink Mug Interior Detail": "Interior detail of pink-speckled mug, glaze pooling softly",
  "Pink Serving Set Close": "Close view of pink serving bowl set",
  "Pink Speckled Mug Close": "Close view of mug with pink speckles across surface",
  "Pink Speckled Mugs Pair": "Matching pair of pink-speckled mugs, delicate color palette",
  "Pink White Spiral Bowl": "Bowl featuring pink and white glaze with spiral center",
  "Pottery Collection Indoor Display": "Indoor display of pottery collection, pieces arranged thoughtfully",
  "Pottery Collection Rooftop Wide": "Expansive rooftop display of handmade pottery, urban skyline framing ceramic landscape",
  "Pottery Display Rooftop Wide Angle": "Wide-angle rooftop pottery collection, city architecture meeting handmade ceramic art",
  "Purple Black Gradient Mug": "Mug with purple to black gradient, dramatic color shift",
  "Purple Black Mug Side View": "Side view of purple-black gradient mug",
  "Purple Blue Gradient Bowl One": "Bowl with purple to blue gradient glaze",
  "Purple Blue Gradient Bowl Three": "Third perspective on gradient glazed bowl",
  "Purple Blue Gradient Bowl Two": "Alternative view of purple-blue gradient bowl",
  "Purple Brown Landscape Mug": "Mug in purple-brown with abstract landscape marks",
  "Purple Gradient Mug": "Mug with purple glaze gradient, color flowing like twilight",
  "Purple Gradient Mug Detail": "Detail of purple gradient mug showing color transition",
  "Purple Green Anatomical Mug": "Mug in purple and green with anatomical heart transfer",
  "Purple Green Bowl Edge Detail": "Edge detail of purple-green glazed bowl",
  "Purple Green Bowl Interior": "Interior of bowl showing purple and green glaze interaction",
  "Purple Speckled Mug": "Mug in purple tones with speckled surface treatment",
  "Small Green Daylily Vase": "Petite vase nestled among daylilies, moss green glaze echoing garden foliage",
  "Smiling Face Transfer Mug": "Mug featuring whimsical smiling face transfer on purple",
  "Soft Cream Bowl Detail": "Intimate detail of cream bowl surface, glaze pooling softly",
  "Soft Cream Bowls Close": "Close view of cream nesting bowls, subtle glaze variations visible",
  "Soft Cream Nesting Bowls": "Nesting bowls in soft cream glaze, gentle forms for everyday beauty",
  "Stacked Moon Face Sculptures": "Whimsical moon face sculptures stacked playfully, each bearing unique carved expression",
  "Sunrise Mugs And Brick Vessels Rooftop": "Sunrise-toned mugs and geometric brick vessels arranged on weathered rooftop surface",
  "Sunrise Mugs Brick Vessels Detail": "Detailed view of sunrise mugs paired with textured brick-shaped vessels",
  "Sunrise Orange Mugs Paired": "Pair of mugs in sunrise orange tones, warm glazes like morning light",
  "Sunset Mug Close Detail": "Close detail of sunset-toned mug, warm color transitions visible",
  "Tall Faceted Vessels": "Tall faceted vessels, geometric and elegant",
  "Teal Burgundy Gallery Vase": "Tall gallery vase with dramatic color blocking, teal green meeting burgundy red in bold geometric division",
  "Textured Bowl Close Detail": "Close detail of heavily textured bowl surface",
  "Textured Earth Mug Carved": "Earth-toned mug bearing deliberate carved marks, texture catching light like ancient stone",
  "Textured Green Moss Covered Vase": "Vase textured like moss-covered bark, thick green glaze organic and wild",
  "Textured Orange And Black Bowl": "Bowl with heavily textured exterior in orange and black, surface rough as volcanic stone",
  "Textured Vessels Group": "Group of textured vessels, varied surface treatments",
  "Textured Vessels Organic Forms": "Vessels with organic textured surfaces, nature-inspired",
  "Three Spiral Bowls Outdoor Display": "Trio of spiral-carved bowls arranged on outdoor stone, each catching afternoon light differently",
  "Triple Layer Gradient Mug": "Mug featuring three-layer glaze gradient, blue to brown to black",
  "Urban Figure Transfer Bowl": "Bowl adorned with urban figure transfers, city life captured in glaze",
  "Urban Figures Bowl Angled": "Angled perspective on urban figure transfer bowl",
  "Urban Figures Bowl Interior": "Interior view of urban figure transfer bowl, skaters and cyclists visible",
  "Urban Figures Bowl Wide": "Wide view of bowl featuring walking urban figures",
  "Urban Life Transfer Bowl Angle": "Angled view of bowl featuring walking figures and urban scenes",
  "White Lidded Jar Cork Top": "Cream-colored lidded jar topped with natural cork stopper, simple and functional form",
  "White Speckled Spiral Bowl Solo": "Single white bowl scattered with dark speckles, spiral carving adding rhythmic dimension",
  "White Spiral Bowl Set Rooftop": "Set of white spiral-carved bowls arranged on rooftop, afternoon shadows adding drama",
  "White Spiral Bowls Trio": "Three white bowls carved with spiral motifs, concentric lines drawing eyes inward like whirlpools",
  "Yarn Bowl And Garlic Keeper": "Yarn bowl alongside garlic keeper with drainage holes, functional pottery for kitchen and craft",
  "Yarn Bowls And Colander Set": "Collection of functional pieces including yarn bowls and berry colander",
};